platform :ios, '9.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'welfare' do
  pod 'MBProgressHUD+BWMExtension', '~> 1.0.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MMDrawerController', :git => 'https://github.com/sisufo/MMDrawerController.git', :commit => 'e591378'
end
